default_context:
  project_name: 'competency spot'
  project_slug: 'skill'
  domain_main: 'skill.com'
  domain_staging: 'stag.skill.com'
  docker_swarm_stack_name_main: 'skill-com'
  docker_swarm_stack_name_staging: 'stag-skill-com'
  secret_key: '99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be6k'
  first_superuser: 'admin@skill.com'
  first_superuser_password: '1234'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.skill.com", "https://stag.skill.com", "https://skill.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@skill.com'
  postgres_password: '1234'
  pgadmin_default_user: 'admin@skill.com'
  pgadmin_default_user_password: '1234'
  traefik_constraint_tag: 'skill.com'
  traefik_constraint_tag_staging: 'stag.skill.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:1234'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
